apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web-server
  template:
    metadata:
      labels:
        app: flask-web-server
    spec:
      containers:
        - name: flask-web-server
          image: karthikmp15/flask-chat-application:1.0.0
          ports:
            - containerPort: 8080  # Flask default port
