apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-web-server
  template:
    metadata:
      labels:
        app: flask-web-server
    spec:
      containers:
        - name: flask-web-server
          image: <your-flask-image>
          ports:
            - containerPort: 5000  # Flask default port
