apiVersion: v1
kind: Service
metadata:
  name: flask-web-server-service
spec:
  selector:
    app: flask-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # The Flask app listens on port 8080
      nodePort: 31100
