apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: 
                      - k8-worker2
                  
      containers:
        - name: mongodb
          image: karthikmp15/mongodb:1.0.0
          ports:
            - containerPort: 27017
          volumeMounts: 
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          hostPath:
            path: /mnt/data/mongodb    
            type: DirectoryOrCreate
